spring.application.name=calendar
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5434/calendar
spring.datasource.username=calendar-ms
spring.datasource.password=${POSTGRES_CALENDAR_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml