spring.application.name=calendar
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/calendar
spring.datasource.username=calendar-ms
spring.datasource.password=${POSTGRES_CALENDAR_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
